#
# Amazon EC2 example cluster configuration
#
ectwo:
    - provider "aws-ec2"					# Optional - default value "aws-ec2"
    - storm-version "0.8.2"					# Version of Storm
    - zk-version "3.3.3"					# Version of Zookeeper
    - image "eu-west-1/ami-480bea3f"				# Template
    - region "eu-west-1"					# Region
    - m1.medium {ZK, WORKER, MASTER, UI}			# Request service
    - m1.medium {ZK, WORKER}					# Request service
    - m1.medium {ZK, WORKER}					# Request service
    - m1.medium {WORKER}					# Request service
    - remote-exec-preconfig {cd ~, echo hey > hey.txt}
    - remote-exec-postconfig {}

#
# CloudStack example cluster configurations
#
cs:
    - provider "cloudstack"
    - provider-endpoint "http://XX.XX.XX.XX:8080/client/api"
    - storm-version "0.8.2"					# Version of Storm
    - zk-version "3.3.3"					# Version of Zookeeper
    - image "Ubuntu 13.10 (64 bit)" 				# Template
    - image-username "cloud"					# Optional - default value "ubuntu"
    - region "ZoneOne" 						# Zone
    - 1/2 {MASTER,ZK,UI,WORKER} 				# Request service
    - remote-exec-preconfig {}
    - remote-exec-postconfig {cd ~, echo hey > hey.txt}

