# Must contain: ZK>=1, MASTER=1, WORKER>=1 (maximally one per instance)
# Optionally UI<=1
#
# EC2 Instancetypes
# 	t1.micro;
#	m1.{small, medium, large, xlarge}
#	c1.{medium, xlarge}
#	m2.{xlarge, 2xlarge, 4xlarge}
#	hi1.{4xlarge}
#	cc1.{4xlarge}
#	cg1.{4xlarge}
#	cc2.{8xlarge}

mycluster:
    - m1.medium {ZK, WORKER, MASTER, UI}
    - m1.medium {ZK, WORKER}
    - m1.medium {ZK, WORKER}
    - m1.medium {WORKER}
    - storm-version "0.8.2"
    - zk-version "3.3.3"
    - image "eu-west-1/ami-480bea3f"
    - region "eu-west-1"
    - remote-exec-preconfig {cd ~, echo hey > hey.txt}
    - remote-exec-postconfig {}
